CREATE DATABASE PREFEITURA_MC;
USE PREFEITURA_MC;

CREATE TABLE SERVIDOR(
	ID INT NOT NULL AUTO_INCREMENT,
	RGF INT NOT NULL,
	NOME VARCHAR(100),
	CARGO VARCHAR(100),
	REGIME VARCHAR(50),
	DT_INCLUSAO DATETIME
);

CREATE TABLE SALARIO(
	ID INT NOT NULL AUTO_INCREMENT,
	ID_SERVIDOR INT NOT NULL,
	ID_LANCAMENTO INT NOT NULL,
	REFERENCIA DATE,
	DESCRICAO VARCHAR(40),
	VALOR DOUBLE,
	DT_INCLUSAO DATETIME
);

CREATE TABLE LANCAMENTO(
	ID INT NOT NULL AUTO_INCREMENT,
	TITULO VARCHAR(15)
);

INSERT INTO LANCAMENTO(TITULO) VALUES ('RENDIMENTO'),('DESCONTO');